ROOT:
  DEV: /home/charlotte/Projekte/devblog
  WEB: /var/www/devblog

TIMESTAMPS:
    FORMAT: "%Y-%m-%d"

TOC:
    LIST_ELEMENT: ol
    MIN_DEPTH: 2

HIGHLIGHT:
    ASSETS_DIR: res
    LEXER: Rust
    THEME: one-dark

PIXELIZER:
    TARGETS:
        - lg 800 75
        - md 600 70
        - sm 400 65
    LAYOUTS:
        - "(max-width: 800px) 100vw"
        - "800px"

AUTO_SUMMARY:
    KEYWORDS: true

AUTO_SEO:
    PRIORITY: 991

COLLECTIONS:
    PRIORITY: 990
    PAGE: tags
    OVERVIEW_TITLE: List of all tags
    OVERVIEW_TEMPLATE: overview.html
    COLLECTION_TEMPLATE: tag.html
